import { PlantInfo, RegiaoInfo, SoloInfo, ProducaoInfo, ProblemaInfo } from './types'

export const PLANT_DATABASE: PlantInfo[] = [
  {
    id: 'tomate',
    nome: 'Tomate',
    nomeCientifico: 'Solanum lycopersicum',
    categoria: 'Hortalica',
    icon: '\uD83C\uDF45',
    phIdeal: '6.0 - 6.8',
    tempIdeal: '20 - 30\u00B0C',
    ciclo: '90 - 120 dias',
    nutrientes: { N: 'alto', P: 'medio', K: 'alto' },
    descricao: 'Planta de clima quente, necessita de boa luminosidade e solo rico em materia organica.',
  },
  {
    id: 'alface',
    nome: 'Alface',
    nomeCientifico: 'Lactuca sativa',
    categoria: 'Hortalica',
    icon: '\uD83E\uDD6C',
    phIdeal: '6.0 - 7.0',
    tempIdeal: '15 - 24\u00B0C',
    ciclo: '45 - 60 dias',
    nutrientes: { N: 'alto', P: 'baixo', K: 'medio' },
    descricao: 'Prefere clima ameno, solo leve e bem drenado com boa umidade.',
  },
  {
    id: 'milho',
    nome: 'Milho',
    nomeCientifico: 'Zea mays',
    categoria: 'Graos',
    icon: '\uD83C\uDF3D',
    phIdeal: '5.5 - 7.0',
    tempIdeal: '24 - 30\u00B0C',
    ciclo: '100 - 150 dias',
    nutrientes: { N: 'muito alto', P: 'medio', K: 'alto' },
    descricao: 'Cultura de grande porte, demanda alta em nitrogenio e boa drenagem.',
  },
  {
    id: 'soja',
    nome: 'Soja',
    nomeCientifico: 'Glycine max',
    categoria: 'Graos',
    icon: '\uD83C\uDF31',
    phIdeal: '6.0 - 6.5',
    tempIdeal: '20 - 30\u00B0C',
    ciclo: '100 - 140 dias',
    nutrientes: { N: 'baixo', P: 'alto', K: 'alto' },
    descricao: 'Leguminosa que fixa nitrogenio. Necessita boa calagem e fosforo.',
  },
  {
    id: 'cafe',
    nome: 'Cafe',
    nomeCientifico: 'Coffea arabica',
    categoria: 'Perene',
    icon: '\u2615',
    phIdeal: '5.5 - 6.5',
    tempIdeal: '18 - 24\u00B0C',
    ciclo: 'Perene (colheita anual)',
    nutrientes: { N: 'alto', P: 'medio', K: 'alto' },
    descricao: 'Cultura perene de meia sombra, necessita solo profundo e bem drenado.',
  },
  {
    id: 'rosa',
    nome: 'Rosa',
    nomeCientifico: 'Rosa spp.',
    categoria: 'Ornamental',
    icon: '\uD83C\uDF39',
    phIdeal: '6.0 - 6.5',
    tempIdeal: '15 - 28\u00B0C',
    ciclo: 'Perene',
    nutrientes: { N: 'medio', P: 'alto', K: 'medio' },
    descricao: 'Planta ornamental que necessita de poda regular e solo rico em fosforo.',
  },
  {
    id: 'orquidea',
    nome: 'Orquidea',
    nomeCientifico: 'Orchidaceae',
    categoria: 'Ornamental',
    icon: '\uD83C\uDF3A',
    phIdeal: '5.5 - 6.5',
    tempIdeal: '18 - 28\u00B0C',
    ciclo: 'Perene',
    nutrientes: { N: 'baixo', P: 'medio', K: 'baixo' },
    descricao: 'Epifita que necessita de substrato arejado e adubacao leve e frequente.',
  },
  {
    id: 'eucalipto',
    nome: 'Eucalipto',
    nomeCientifico: 'Eucalyptus spp.',
    categoria: 'Florestal',
    icon: '\uD83C\uDF33',
    phIdeal: '5.0 - 6.0',
    tempIdeal: '18 - 30\u00B0C',
    ciclo: '5 - 7 anos (corte)',
    nutrientes: { N: 'medio', P: 'alto', K: 'alto' },
    descricao: 'Arvore de rapido crescimento, alta demanda de fosforo na fase inicial.',
  },
  {
    id: 'morango',
    nome: 'Morango',
    nomeCientifico: 'Fragaria x ananassa',
    categoria: 'Fruta',
    icon: '\uD83C\uDF53',
    phIdeal: '5.5 - 6.5',
    tempIdeal: '13 - 26\u00B0C',
    ciclo: '60 - 90 dias (producao)',
    nutrientes: { N: 'medio', P: 'alto', K: 'alto' },
    descricao: 'Fruta de clima temperado, necessita solo acido e rico em materia organica.',
  },
  {
    id: 'cana',
    nome: 'Cana-de-acucar',
    nomeCientifico: 'Saccharum officinarum',
    categoria: 'Industrial',
    icon: '\uD83C\uDF3E',
    phIdeal: '5.5 - 6.5',
    tempIdeal: '25 - 35\u00B0C',
    ciclo: '12 - 18 meses',
    nutrientes: { N: 'alto', P: 'medio', K: 'muito alto' },
    descricao: 'Cultura tropical de grande porte, alta demanda de potassio.',
  },
  {
    id: 'pimentao',
    nome: 'Pimentao',
    nomeCientifico: 'Capsicum annuum',
    categoria: 'Hortalica',
    icon: '\uD83C\uDF36\uFE0F',
    phIdeal: '5.5 - 6.8',
    tempIdeal: '21 - 30\u00B0C',
    ciclo: '90 - 120 dias',
    nutrientes: { N: 'medio', P: 'medio', K: 'alto' },
    descricao: 'Sensivel ao frio, necessita solo fertil e boa irrigacao.',
  },
  {
    id: 'manga',
    nome: 'Manga',
    nomeCientifico: 'Mangifera indica',
    categoria: 'Fruta',
    icon: '\uD83E\uDD6D',
    phIdeal: '5.5 - 7.0',
    tempIdeal: '24 - 30\u00B0C',
    ciclo: 'Perene (colheita anual)',
    nutrientes: { N: 'medio', P: 'medio', K: 'alto' },
    descricao: 'Arvore tropical de grande porte que produz melhor em climas quentes e secos.',
  },
]

export const REGIOES: RegiaoInfo[] = [
  { id: 'norte', nome: 'Norte', estados: 'AM, PA, AC, RO, RR, AP, TO', clima: 'Equatorial', soloTipico: 'Latossolo Amarelo', caracteristicas: 'Alta pluviosidade, temperatura elevada, solo acido' },
  { id: 'nordeste', nome: 'Nordeste', estados: 'MA, PI, CE, RN, PB, PE, AL, SE, BA', clima: 'Tropical / Semiarido', soloTipico: 'Latossolo Vermelho / Neossolo', caracteristicas: 'Irregular pluviosidade, alta evaporacao, solos variados' },
  { id: 'centro-oeste', nome: 'Centro-Oeste', estados: 'MT, MS, GO, DF', clima: 'Tropical', soloTipico: 'Latossolo Vermelho', caracteristicas: 'Cerrado predominante, solo acido com aluminio toxico' },
  { id: 'sudeste', nome: 'Sudeste', estados: 'SP, RJ, MG, ES', clima: 'Tropical / Subtropical', soloTipico: 'Latossolo Vermelho-Amarelo', caracteristicas: 'Diversidade climatica, solos medios a ferteis' },
  { id: 'sul', nome: 'Sul', estados: 'PR, SC, RS', clima: 'Subtropical', soloTipico: 'Latossolo Vermelho / Nitossolo', caracteristicas: 'Clima temperado, geadas, solos mais ferteis' },
]

export const TIPOS_SOLO: SoloInfo[] = [
  { id: 'arenoso', nome: 'Arenoso', descricao: 'Leve, drena rapido, pouca retencao de nutrientes', correcao: 'Adicionar materia organica e argila', icon: '\uD83C\uDFD6\uFE0F' },
  { id: 'argiloso', nome: 'Argiloso', descricao: 'Pesado, retencao de agua, compactacao', correcao: 'Adicionar areia e materia organica para aerar', icon: '\uD83E\uDDF1' },
  { id: 'siltoso', nome: 'Siltoso', descricao: 'Intermediario, boa retencao, erosao facil', correcao: 'Cobertura vegetal e materia organica', icon: '\uD83C\uDF3E' },
  { id: 'humoso', nome: 'Humoso / Organico', descricao: 'Rico em materia organica, escuro, fertil', correcao: 'Geralmente nao necessita grande correcao', icon: '\uD83C\uDF31' },
  { id: 'latossolo', nome: 'Latossolo (Cerrado)', descricao: 'Profundo, acido, pobre em nutrientes, bem drenado', correcao: 'Calagem + fosfatagem + adubacao completa', icon: '\uD83D\uDFE5' },
]

export const TIPOS_PRODUCAO: ProducaoInfo[] = [
  { id: 'vaso', nome: 'Vaso / Jardineira', descricao: 'Cultivo domestico em recipientes', icon: '\uD83E\uDEB4', escala: 'Micro' },
  { id: 'horta', nome: 'Horta Domestica', descricao: 'Canteiros pequenos em residencias', icon: '\uD83C\uDFE1', escala: 'Pequena' },
  { id: 'estufa', nome: 'Estufa / Viveiro', descricao: 'Ambiente controlado para producao de mudas', icon: '\uD83C\uDFED', escala: 'Media' },
  { id: 'pequena', nome: 'Pequena Propriedade', descricao: 'Ate 4 modulos fiscais - agricultura familiar', icon: '\uD83C\uDF3E', escala: 'Pequena-Media' },
  { id: 'media', nome: 'Media Propriedade', descricao: 'Producao comercial regional', icon: '\uD83D\uDE9C', escala: 'Media-Grande' },
  { id: 'larga', nome: 'Larga Escala', descricao: 'Agronegocio - producao em grande escala', icon: '\uD83C\uDF3D', escala: 'Grande' },
]

export const PROBLEMAS: ProblemaInfo[] = [
  { id: 'pragas_insetos', nome: 'Pragas (Insetos)', descricao: 'Pulgoes, cochonilhas, lagartas, acaros', icon: '\uD83D\uDC1B', categoria: 'biologico' },
  { id: 'fungos', nome: 'Fungos / Doencas', descricao: 'Oidio, ferrugem, manchas foliares', icon: '\uD83C\uDF44', categoria: 'biologico' },
  { id: 'deficiencia_n', nome: 'Deficiencia de Nitrogenio', descricao: 'Folhas amareladas, crescimento lento', icon: '\uD83C\uDF43', categoria: 'nutricional' },
  { id: 'deficiencia_p', nome: 'Deficiencia de Fosforo', descricao: 'Folhas arroxeadas, raiz fraca', icon: '\uD83C\uDF42', categoria: 'nutricional' },
  { id: 'deficiencia_k', nome: 'Deficiencia de Potassio', descricao: 'Bordas das folhas queimadas', icon: '\uD83C\uDF41', categoria: 'nutricional' },
  { id: 'solo_acido', nome: 'Solo Acido', descricao: 'pH baixo, toxidez por aluminio', icon: '\u26A0\uFE0F', categoria: 'solo' },
  { id: 'compactacao', nome: 'Solo Compactado', descricao: 'Dificuldade de drenagem e raizes', icon: '\uD83E\uDDF1', categoria: 'solo' },
  { id: 'excesso_agua', nome: 'Excesso de Agua', descricao: 'Encharcamento, raizes apodrecendo', icon: '\uD83D\uDCA7', categoria: 'manejo' },
  { id: 'seca', nome: 'Estresse Hidrico (Seca)', descricao: 'Murcha, folhas enrolando', icon: '\u2600\uFE0F', categoria: 'manejo' },
  { id: 'nenhum', nome: 'Nenhum Problema', descricao: 'Planta saudavel, apenas busca otimizacao', icon: '\u2705', categoria: 'nenhum' },
]
